"""
Agent state definition for the LangGraph autonomous data analyst.

This module defines the AgentState TypedDict that holds all state
throughout the agent execution graph.
"""

from typing import TypedDict, Annotated, List, Optional
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    """
    State object that flows through all nodes in the LangGraph agent.

    This state is updated by each node and persists across the entire
    analysis session via LangGraph checkpointing.
    """

    # ========== Core Inputs ==========
    dataset_path: str
    """Absolute path to the uploaded CSV/Excel file"""

    user_goal: str
    """Natural language description of the analysis goal from the user"""

    session_id: str
    """Unique identifier for this analysis session"""

    # ========== Planning ==========
    plan: List[str]
    """Ordered list of sub-tasks generated by the planner node"""

    current_step: int
    """Index of the current step being executed (0-indexed)"""

    # ========== Coding ==========
    generated_code: str
    """The most recent Python code generated by the coder node"""

    code_history: List[str]
    """Historical record of all code versions for debugging context"""

    # ========== Execution ==========
    execution_result: Optional[str]
    """Standard output from successful code execution"""

    execution_error: Optional[str]
    """Error message / traceback if code execution failed"""

    retry_count: int
    """Number of times the critic has attempted to fix the current step"""

    # ========== Outputs ==========
    charts: List[str]
    """List of base64-encoded PNG chart images generated during analysis"""

    insights: str
    """Final natural language summary of findings from the summarizer node"""

    # ========== Streaming ==========
    messages: Annotated[list, add_messages]
    """Message history for real-time WebSocket streaming to frontend"""
